### PR TITLE
Fixed bug in timestamp used in *png and *npy filenames.

### PR DESCRIPTION
**Pull request by liamconnor**

### CODE REVIEW

**Comment by kiyo-masui** [comment]
Cn you strip out the extra `t_unix = time.time()` on line 208?

**Comment by liamconnor** [comment]
Sorry, why is it extra, I don't see another time.time()? I use it to identify the creation-time and make multiple copies if the same *png *npy files in case I need to search the data again.

**Comment by kiyo-masui** [comment]
Oh I see, sorry I missed that further down.

Instead of changing the naming scheme to include a not-entirely-relevant search time, could we instead just check for a previously existing file and append an integer?

**Comment by liamconnor** [comment]
OK, will do that next. What do you think about my removing the whole DM5-20, 20-100, etc. and just writing the actual dispersion measure into the filename? Much easier to skim through when triggers are pouring in.

**Comment by kiyo-masui** [comment]
Yeah, that sounds good. Rounding to an integer.

Kiyo

**Comment by liamconnor** [comment]
Made the discussed changes. Now writes a %02d integer as a trigger version number.

**Comment by kiyo-masui** [comment]
Whoops, looks like you might have clobbered some lines I added further down in process_real_time().

**Comment by liamconnor** [comment]
Sorry, should be replaced.

**Comment by kiyo-masui** [comment]
Sorry to nit-pic, but in the file diff, the very last change moves the location of the logging output down a line. The location of this actually matters a bit since the call to get_next_block can block while it waits for data from another thread. Can you move this back? Then I'll merge.

**Comment by liamconnor** [comment]
Sorry, forgot about this. Does this PR make sense now?

**Pull request merged**
